services:

  #
  # janus-gateway
  #
  janus-gateway:
    image: 'rst/janus-gateway:latest'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
      - "./config/:/usr/local/etc/janus/"
    restart: always

